Models/CourseViewModel.cs
namespace KUSYS_Demo.Models
{
    public class CourseViewModel
    {
        public int Id { get; set; }
        public string? CourseId { get; set; }
        public string? CourseName { get; set; }
    }
}

Models/Entities/Course.cs
using System.ComponentModel.DataAnnotations;

namespace KUSYS_Demo.Models.Entities
{
    public class Course : IEntity
    {
        [Key]
        public int Id { get; set; } 
        public string? CourseId { get; set; }
        public string? CourseName { get; set; }
    }
}

Models/Entities/IEntity.cs
namespace KUSYS_Demo.Models.Entities
{
    public interface IEntity
    {
    }
}

Models/Entities/Student.cs
namespace KUSYS_Demo.Models.Entities
{
    public class Student : IEntity
    {
        public int StudentId { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public DateTime BirthDate { get; set; }
        public int CourseId { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace KUSYS_Demo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/StudentUpdateViewModel.cs
using KUSYS_Demo.Models.Entities;

namespace KUSYS_Demo.Models
{
    public class StudentUpdateViewModel: StudentViewModel
    {
        public int CourseId { get; set; }
        public List<Course>? Courses { get; set; }
    }
}

Models/StudentViewModel.cs
namespace KUSYS_Demo.Models
{
    public class StudentViewModel
    {
        public int StudentId { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public DateTime BirthDate { get; set; }
        public string CourseName { get; set; }
    }
}

Controllers/CourseController.cs
using KUSYS_Demo.Models;
using KUSYS_Demo.Models.Entities;
using KUSYS_Demo.Repository;
using Microsoft.AspNetCore.Mvc;

namespace KUSYS_Demo.Controllers
{
    public class CourseController : Controller
    {
        ICourseRepository _courseRepository;

        public CourseController(ICourseRepository courseRepository)
        {
            _courseRepository = courseRepository;
        }

        public IActionResult Index()
        {
            List<Course> courses = _courseRepository.GetAll();
            List<CourseViewModel> list = new List<CourseViewModel>();
            foreach (var item in courses)
            {
                CourseViewModel courseView = new CourseViewModel()
                {
                    Id = item.Id,
                    CourseId = item.CourseId,
                    CourseName = item.CourseName,
                };
                list.Add(courseView);
            }

            return View(list);
        }
        [HttpGet]
        public IActionResult Insert()
        {
            return View();
        } 
        [HttpPost]
        public IActionResult Insert(Course course)
        {
            _courseRepository.Add(course);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            _courseRepository.Delete(new Course { Id=id});
            return RedirectToAction(nameof(Index));
        }


    }
}

Controllers/HomeController.cs
using KUSYS_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KUSYS_Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentController.cs
using KUSYS_Demo.Models;
using KUSYS_Demo.Models.Entities;
using KUSYS_Demo.Repository;
using Microsoft.AspNetCore.Mvc;

namespace KUSYS_Demo.Controllers
{
    public class StudentController : Controller
    {
        ICourseRepository _courseRepository;
        IStudentRepository _studentRepository;

        public StudentController(ICourseRepository courseRepository, IStudentRepository studentRepository)
        {
            _courseRepository = courseRepository;
            _studentRepository = studentRepository;
        }


        public IActionResult Index()
        {
            List<Student> students = _studentRepository.GetAll();
            List<StudentViewModel> list = new List<StudentViewModel>();
            foreach (var item in students)
            {
                var course = _courseRepository.GetById(item.CourseId);
                StudentViewModel studentView = new StudentViewModel()
                {
                    StudentId = item.StudentId,
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    BirthDate = item.BirthDate,
                    CourseName = course.CourseName != null ? course.CourseName : string.Empty,
                };
                list.Add(studentView);
            }

            return View(list);
        }
        [HttpGet]
        public IActionResult Insert()
        {
            List<Course> courses = _courseRepository.GetAll();
            List<CourseViewModel> list = new List<CourseViewModel>();
            foreach (var item in courses)
            {
                CourseViewModel courseView = new CourseViewModel()
                {
                    Id = item.Id,
                    CourseId = item.CourseId,
                    CourseName = item.CourseName,
                };
                list.Add(courseView);
            }

            return View(list);
        }
        [HttpPost]
        public IActionResult Insert(Student student)
        {
            _studentRepository.Add(student);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var student=_studentRepository.GetById(id);
            var course = _courseRepository.GetById(student.CourseId);

            StudentUpdateViewModel studentView = new StudentUpdateViewModel()
            {
                StudentId = student.StudentId,
                FirstName = student.FirstName,
                LastName = student.LastName,
                BirthDate = student.BirthDate,
                Courses = _courseRepository.GetAll(),
                CourseName = course.CourseName != null ? course.CourseName : string.Empty,
                CourseId = course.Id
            };

            return View(studentView);
            
        }

        [HttpPost]
        public ActionResult Update(Student student)
        {
            _studentRepository.Update(student);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            _studentRepository.Delete(new Student { StudentId = id });
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Course/Index.cshtml
@{
    ViewData["Title"] = "Kurslar";
}
@model List<CourseViewModel>
<br />
<br />
<br />
<a href="@Url.Action("Insert","Course")" class="btn btn-success">Kurs Ekle</a>
<table class="table table-bordered">
    <tbody>
        <tr>
            <td>Id</td>
            <td>İsmi</td>
            <td>Sil</td>
        </tr>
        @foreach (CourseViewModel course in Model)
        {
            <tr>
                <td>@course.CourseId</td>
                <td>@course.CourseName</td>
                <td><a href="@Url.Action("Delete","Course",new {id = course.Id})" class="btn btn-danger">Sil</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Course/Insert.cshtml
@{
    ViewData["Title"] = "Kurs Ekle";
}

<br />
<br />
<br />
@using (Html.BeginForm("Insert", "Course", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <div class="form-group">
            <input type="text" name="CourseId" placeholder="Kurs Id" class="form-control" required />
        </div>
        <div class="form-group">
            <input type="text" name="CourseName" placeholder="Kurs İsmi" class="form-control" required />
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Ekle" />
        </div>
    </div>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Anasayfa";
}


<a href="@Url.Action("Insert","Student")" class="btn btn-success"> Öğrenci Ekle</a>
<a href="@Url.Action("Insert","Course")" class="btn btn-success"> Kurs Ekle</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KUSYS_Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KUSYS_Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KUSYS_Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Öğrenci</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Kurslar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - KUSYS_Demo - <a asp-area="" asp-controller="Student" asp-action="Index">Öğrenci</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Index.cshtml
@{
    ViewData["Title"] = "Öğrenci";
}
@model List<StudentViewModel>
<br />
<br />
<br />
<a href="@Url.Action("Insert","Student")" class="btn btn-success"> Öğrenci Ekle</a>
<table class="table table-bordered">
    <tbody>
        <tr>
            <td>Id</td>
            <td>İsmi</td>
            <td>Soyismi</td>
            <td>Doğum Tarihi</td>
            <td>Kurs Adı</td>
        </tr>
        @foreach (StudentViewModel student in Model)
        {
            <tr>
                <td>@student.StudentId</td>
                <td>@student.FirstName</td>
                <td>@student.LastName</td>
                <td>@student.BirthDate</td>
                <td>@student.CourseName</td>
                <td><a href="@Url.Action("Update","Student",new {id = student.StudentId })" class="btn btn-default">Düzenle</a></td>
                <td><a href="@Url.Action("Delete","Student",new {id = student.StudentId})" class="btn btn-danger">Sil</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Student/Insert.cshtml
@{
    ViewData["Title"] = "Kurs Ekle";
}
@model List<CourseViewModel>

<br />
<br />
<br />
@using (Html.BeginForm("Insert", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <div class="form-group">
            <input type="text" name="FirstName" placeholder="Adı" class="form-control" required />
        </div>
        <div class="form-group">
            <input type="text" name="LastName" placeholder="Soyadı" class="form-control" required />
        </div>
        <div class="form-group">
            <input type="date"  name="BirthDate" placeholder="31/12/2016" class="form-control" required />
        </div>
        <div class="form-group">
            <select name="CourseId" class="form-control required" placeholder="Kurs İsmi">
                @foreach (var item in Model)
                {
                    <option value="@item.Id">@item.CourseName</option>
                }
            </select>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Ekle" />
        </div>
    </div>
}

Views/Student/Update.cshtml
@{
    ViewData["Title"] = "Kurs Ekle";
}
@model StudentUpdateViewModel

<br />
<br />
<br />
@using (Html.BeginForm("Update", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <div class="form-group">
            <input type="text" name="FirstName" placeholder="Adı" value="@Model.FirstName" class="form-control" required />
        </div>
        <div class="form-group">
            <input type="text" name="LastName" placeholder="Soyadı" value="@Model.LastName" class="form-control" required />
        </div>
        <div class="form-group">
            <input type="datetime-local" name="BirthDate" value="@Model.BirthDate" class="form-control" required />
        </div>
        <div class="form-group">
            <select name="CourseId" class="form-control required" placeholder="Kurs İsmi">
                <option value="@Model.CourseId">@Model.CourseName</option>
                @foreach (var item in Model.Courses)
                {
                    <option value="@item.Id">@item.CourseName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <input type="hidden" name="StudentId" value="@Model.StudentId" />
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Kaydet" />
        </div>
    </div>
}